### ISSUE TITLE
Villagers are not feared from Jack'o'Lanterns

### ISSUE THREAD

**Issue by garantiertnicht** [Ellpeck/PumpkiSplode#4]
These are even scarier then pumpkins, so that should definitely cause an explosion 😨 
![2017-02-04_11 51 06](https://cloud.githubusercontent.com/assets/7950273/22617934/95093128-ead0-11e6-92f2-f62197b50cb9.png)

**Comment by Ellpeck** [comment]
They're lit, so they're cozy.
