### ISSUE TITLE
Villagers are not scared of other villagers that wear pumpkins

### ISSUE THREAD

**Issue by garantiertnicht** [Ellpeck/PumpkiSplode#5]
Such villagers can easily be created with a dispenser
![2017-02-04_11 55 14](https://cloud.githubusercontent.com/assets/7950273/22617984/cf8add3c-ead1-11e6-9944-f26190a3b5d5.png)

**Comment by Ellpeck** [comment]
Every entity's armor inventory works a little differently. I'm not going to implement this for every one. Just accept this, it's a joke mod, be done with it, thanks.

**Comment by garantiertnicht** [comment]
Also applies to zombies. Zombies can naturally spawn with Pumpkins at halloween, and this _should_ cause a mass armageddon imo. You can spawn them with `/summon Zombie ~ ~ ~ {ArmorItems:[{},{},{},{id:minecraft:pumpkin}]}` outside of halloween and here is the result:
![2017-02-04_12 06 21](https://cloud.githubusercontent.com/assets/7950273/22618022/a78ff6fe-ead2-11e6-906a-46391d806ac5.png)
